abacritt/angularx-social-login

- src/providers/facebook-login-provider.ts
As commented on issue #18 
Regards
> Fix twice call to fb_page_view

- src/entities/user.ts
- src/providers/google-login-provider.ts
For google authentication there is a [token](https://developers.google.com/identity/sign-in/web/backend-auth) that can be sent to backend and the backend validates this information with google. I added this token in user and changed the google provider to get this token from google response.
> add token_id (google) in the user

- src/lib/src/auth.service.ts
This wil give the option to handle signin errors from outside
> Added a call to reject method when provider signIn fails

- package.json
- src/lib/index.ts
- src/lib/src/auth.service.ts
- src/lib/src/entities/login-provider.ts
- src/lib/src/providers/google-login-provider.ts
Added option that solves #66 and adds the new option for Google Login.
> Added new LoginOpt to be able to use the 'prompt' option on Google Login.

- src/lib/src/providers/facebook-login-provider.ts
Add else statement to handle login cancellation according to https://developers.facebook.com/docs/reference/javascript/FB.login/v3.0
> Issue #112. Handle facebook login popup closed by user

- src/lib/src/providers/google-login-provider.ts
> Handle google login popup closed by user

- src/lib/src/auth.service.ts
- src/lib/src/entities/base-login-provider.ts
- src/lib/src/entities/login-provider.ts
- src/lib/src/providers/facebook-login-provider.ts
- src/lib/src/providers/google-login-provider.ts
@jaibatrik as you requested [here](https://github.com/abacritt/angularx-social-login/issues/110#issuecomment-407708575), I added the possibility to completely revoke the user authorization with a parameter on the SignOut method of the provider.
[Here](https://developers.google.com/identity/protocols/OAuth2UserAgent) you can see Google provides two different methods: SignOut and Disconnect;
Since it is a optional parameter, it won't be harmful calling SigOut function with others login providers.
> Added "revoke" optional param to Google SignOut method

- src/lib/src/providers/linkedIn-login-provider.ts
@jaibatrik Please review the PR for Linked API 400 error response.
> LinkedIn API request 400 fix

- src/lib/src/auth.service.ts
According to this issue: https://github.com/abacritt/angularx-social-login/issues/158
Added lazy loading for SDKs. Downloading of SDKs is performed on the first call of `authService.signIn()` or `authService.signOut()`.
Before calling `authService.signIn()` or `authService.signOut()` we have only our own cookies:
and after calling some of these methods we have additional socail cookies:
Such behavior is active when some of `AuthServiceConfigItem` has field `lazyLoad` as `true`. e.g.:
```
{
id: FacebookLoginProvider.PROVIDER_ID,
provider: new FacebookLoginProvider('561602290896109'),
lazyLoad: true
},
```
> First version of lazy loading

- build.js
- package-lock.json
- package.json
> Upgrade to Angular v8.x

- build.js
Fixes #185.
See https://github.com/rollup/rollup/issues/794#issuecomment-270803587
> Suppress the "This keyword is undefined" build warnings

- src/lib/auth.service.ts
I made it possible for AuthServiceConfig to accept an Observable as well as a provider list. This should resolve issue #122.
> #122 AuthServiceConfig can now also accept an observable

- projects/lib/src/socialauth.service.ts
> fix: if autologin return null if not logged in

- README.MD
- microsoft-provider.md
- projects/lib/src/providers/microsoft-login-provider.ts
Fixes missing `user.authToken` that I had forgot to set for the Microsoft Provider in #338
> Microsoft Provider Cleanup and Detailed Documentation

- projects/lib/src/entities/social-user.ts
- projects/lib/src/providers/google-login-provider.ts
Fixed AuthResponse issue for google login provider
> Fixed auth response for google login provider #365

- projects/lib/src/providers/microsoft-login-provider.ts
Fixes https://github.com/abacritt/angularx-social-login/issues/404
> Use minified build of `msal`

- README.MD
Only the path declaration "angularx-social-login" in the import doesn't work.
> Fixing From imports

- README.MD
Add document for additional options: type and size for GoogleSigninButtonDirective base on PR https://github.com/abacritt/angularx-social-login/pull/547
> Update document for GoogleSigninButtonDirective

- projects/lib/README.md
- projects/lib/src/providers/vk-login-provider.ts
I have noticed recently that VK provider doesn't support scopes which define the access level. For instance, you may request access to email, photos, friend list, notifications, etc.
> Vk provider scopes

- src/app/app.component.ts
- src/app/app.config.ts
- src/app/demo/demo.component.html
- src/app/demo/demo.component.ts
- src/app/navbar/navbar.component.ts
- src/main.ts
This small PR fixes the standalone API usage in the demo application.
> Fix standalone usage
