abacritt/angularx-social-login

- src/providers/google-login-provider.ts
This could let users implement their own google login provider, storing token variables in custom user object class instance.
> make auth variable accessible for extending classes

- README.MD
The example in the readme for importing this module doesn't work. The app.module.ts in the demo page (https://abacritt.github.io/angularx-social-login/main.bundle.js) is setup correctly and works though. I made sure by testing the code from the demo in my own app as well. I copied the configuration into this readme.
> Fixed README example

- src/lib/src/auth.service.ts
- src/lib/src/entities/base-login-provider.ts
- src/lib/src/entities/login-provider.ts
- src/lib/src/providers/facebook-login-provider.ts
- src/lib/src/providers/google-login-provider.ts
- src/lib/src/providers/linkedIn-login-provider.ts
Fixes problem with the SDK's not being available yet or `login` functions being called before `init` functions. https://github.com/abacritt/angularx-social-login/issues/93
The error was reported (and experienced myself) only for Facebook, but I believe the error could happen both for Google and Linked In as well and so I made a generic solution for all 3 providers. I've only really tested it for Facebook though.
As you call `AuthService.signIn` or `AuthService.signOut` each provider will internally make sure that the SDK is actually ready before attempting to do the call by using the new `protected onReady(): Promise<void>` in the `BaseLoginProvider`.
Additionally the `AuthService` will expose a new observable called `readyState` which will emit a string array with the `PROVIDER_ID` of …
> add ready state for providers

- src/lib/src/entities/user.ts
- src/lib/src/providers/facebook-login-provider.ts
- src/lib/src/providers/linkedIn-login-provider.ts
Fixes https://github.com/abacritt/angularx-social-login/issues/100 for Facebook and Linked In.
```typescript
new AuthServiceConfig([{
id: FacebookLoginProvider.PROVIDER_ID,
provider: new FacebookLoginProvider(
'Facebook-App-Id',
{ scope: 'email,user_age_range' },
'en_US',
'name,email,picture,first_name,last_name,age_range' // this parameter is new
)
}]);
```
The resulting SocialUser will now contain the entire resulting object in the property `facebook` or `linkedIn` respectively.
```typescript
this.authService.signIn(FacebookLoginProvider.PROVIDER_ID).then((user: SocialUser) => {
console.log(user.facebook.age_range); // { "min": 21 }
});
```
This example shows Facebook only, but Linked In works exactly the same way.
However, this PR does **not** include Google as their API seems to work …
> add ability to choose which fields to get

- src/lib/src/providers/facebook-login-provider.ts
#109 
``` javascript
new AuthServiceConfig([{
id: FacebookLoginProvider.PROVIDER_ID,
provider: new FacebookLoginProvider(
'Facebook-App-Id',
{ scope: 'email,user_age_range' },
'en_US',
'name,email,picture,first_name,last_name,age_range',
'v2.12' // NEW PARAMETER
)
}]);
```
> ASL-109 Add the ability to change the default Facebook SDK version

- src/lib/src/providers/facebook-login-provider.ts
Using fat arrow notation to get correct reference to the object instead of scope of the function.
> getLoginStatus: correct ref to this

- src/lib/src/auth.service.ts
- src/lib/src/providers/facebook-login-provider.ts
- src/lib/src/providers/google-login-provider.ts
- src/lib/src/providers/linkedIn-login-provider.ts
Rejecting the getLoginStatus in each provider when a user is not logged allows to react on this when a user is fetching the authState when the application is bootstrapped for the first time.
Fixes #154
> {bug} Reject getLoginStatus when no user is logged in

- src/lib/src/providers/facebook-login-provider.ts
Since type is not defined, the previous version of Typescript complains as 
"error TS1039: Initializers are not allowed in ambient contexts."
> Adding Type to PROVIDER_ID

- src/index.ts
- src/lib/providers/apple-login-provider.ts
Apple.js use callback Post to send User Information.
You must have a new Endpoint
Init in your App.module
{
id: AppleLoginProvider.PROVIDER_ID,
provider: new AppleLoginProvider('[CLIENT_ID]','name email', '[REDIRECT_URI]')
}
> #240 Add Apple Signin

- src/lib/src/sociallogin.module.ts
The SocialLoginModule should only be included once in an Angular application.
Implementing an error handling logic according to the Angular
documentation at:
https://angular.io/guide/singleton-services#prevent-reimport-of-the-core
module
> refactor(sociallogin.module.ts): SocialLoginModule refacoring

- README.MD
- package-lock.json
- src/index.ts
- src/lib/providers/dummy-login-provider.ts
- src/lib/providers/index.ts
A login provider that simulates a social login without requiring remote network access or application registration with any third party authentication provider.  Allows custom configuration of dummy authenticated user details.
> Simple DummyLoginProvider

- projects/lib/src/socialauth.service.ts
It's not intuitive and makes some restrictions when you do not emit this event.
1 - **Subscribe** on this subject never fires. And you need to use a **finalize** pipe and leave an empty subscribe to get the state of observable. It's a little bit redundant code.
```
this.socialAuthService.initState
.pipe(finalize(() => this.socialAuthServiceInitialized = true))
.subscribe();
```
2 - You can't use it in angular **async** pipe. For example:
```
<button type="button" [disabled]="disabled || !(socialAuthService.initState | async)">Continue with Facebook</button>
```
> Emit initState event

- projects/lib/src/socialauth.service.ts
With google or other providers you can get following error when you are browsing in private modus:
```error: "idpiframe_initialization_failed", details: "Cookies are not enabled in current environment."```
In this case I want to inform the user instead of having a silence error. My proposal is to add an erroCallback, where you can add an alert or something else to avoid that the user is not informed.
> feat: add optional errorCallback

- projects/lib/src/providers/microsoft-login-provider.ts
- projects/lib/src/public-api.ts
- src/app/app.module.ts
- src/app/demo/demo.component.html
- src/app/demo/demo.component.ts
- src/index.html
Resolves: https://github.com/abacritt/angularx-social-login/issues/306
Logout for the Microsoft provider has to navigate to `login.microsoftonline.com` to fully end the user session and log them out.  I opened an issue against the MSAL library ( https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2563 ) so worst case we could do that in a popup like the login and they seem to have had that request a few times already.
**Configuration**
Default configuration looks like the following which is just a flattening of commonly used properties from the [MSAL configuration object](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md).
```typescript
const COMMON_AUTHORITY: string = …
```
> Microsoft Login Provider

- projects/lib/src/providers/microsoft-login-provider.ts
Fixes the undesired behavior from Microsoft logout from #306.
**Behavior before commit**
When logging out of Microsoft, the page navigates to the Microsoft authentication site then sends us back to our app's url. This isn't the desired behavior in a SPA.
**Behavior after commit**
When loggin out of Microsoft, a popup opens and logs the user out. This behavior is similar to a login popup which is better than navigating to another page. Documentation of Microsoft logout can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/187a32f2381d143825a8f48f571c9f9322d6aa51/lib/msal-browser/docs/logout.md).
> Microsoft logout with popup instead of page navigation

- microsoft-provider.md
- projects/lib/src/providers/microsoft-login-provider.ts
Add `prompt` option to indicate user interaction type during login process.
[Send Sign In request from MS documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#send-the-sign-in-request)
> MS Provider - prompt option

- projects/lib/src/providers/google-login-provider.ts
- Change google endpoint
- Change entity to load
- Minor eslint fixes
closes #442 
PS: Please test it!
> Migrate to the new Google Identity Services library

- README.MD
Images won't show and a 403 is generated when using the photoUrl of google.
See: https://stackoverflow.com/questions/40570117/http403-forbidden-error-when-trying-to-load-img-src-with-google-profile-pic
This fixes that in the readme so the sample works OOB.
> fix(readme): img src when using google provider

- projects/lib/src/providers/google-login-provider.ts
Google is now throwing an error if deprecated APIs are used. This change cures this problem by still allowing the use of the auth object. All other errors are still rejected. After this change the Google provider will need to be completely re-written for the new API. Note the new API is not compatible with the old one and so there will have to be a fall back period whilst users upgrade.
> Correct google init action if an error is seen

- projects/lib/package.json
The peer dependency constraint was requiring the version to be >= 13.2.6, but there seem to be no actual need for the changes introduced after the release.
Fixes https://github.com/abacritt/angularx-social-login/issues/463
> Support all Angular 13 versions

- projects/lib/src/entities/base-login-provider.ts
- projects/lib/src/entities/login-provider.ts
- projects/lib/src/providers/google-login-provider.ts
- projects/lib/src/socialauth.service.ts
- src/app/app.module.ts
- Since LoginProvider & BaseLoginProvider are exported from the lib, as consumers we can implement our own login providers.
That's good but we seem forced to [create our login provider instances directly](https://github.com/abacritt/angularx-social-login/blob/master/src/app/app.module.ts#L26-L53) when we provide a value for `SocialAuthServiceConfig`, and we have no easy way to inject other services in our custom login providers.
This PR should make something like this possible
```typescript
@Injectable({ providedIn: 'root' })
export class MyCustomLoginProvider extends BaseLoginProvider {
public static readonly PROVIDER_ID = 'CUSTOM' as const;
constructor(/* infinite list of dependencies*/) {}
}
...
@NgModule({
declarations: [AppComponent, NavbarComponent, DemoComponent],
imports: …
```
> injectable login providers + SRP

- projects/lib/src/providers/google-login-provider.ts
For Google login, it fails when decoding the jwt token in multibyte languages.
Error in function decodeJwt:
```
Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
at GoogleLoginProvider.decodeJwt (http://localhost:4200/main.js:537:30)
at GoogleLoginProvider.createSocialUser (http://localhost:4200/main.js:526:26)
```
> fixes "atob" decode failed to execute

- README.MD
- projects/lib/src/directives/google-signin-button.directive.ts
I added `itp_support` boolean attribute to `GoogleSigninButtonDirective`. This allows users to disable the One Tap window in case we just want the button.
Sources :
[HTML API reference : data-itp_support](https://developers.google.com/identity/gsi/web/reference/html-reference#data-itp_support)
[Understand One Tap User Experience : Upgraded UX on ITP browsers](https://developers.google.com/identity/gsi/web/guides/features#upgraded_ux_on_itp_browsers)
Example :
> [Add] itp_support attr to Google btn

- README.MD
- projects/lib/src/directives/google-signin-button.directive.ts
- projects/lib/src/providers/google-login-provider.ts
Reverts abacritt/angularx-social-login#581 thanks to [kattoshi](https://github.com/kattoshi)
Move `itp_support` from [GsiButtonConfiguration](https://developers.google.com/identity/gsi/web/reference/js-reference#GsiButtonConfiguration) to [IdConfiguration](https://developers.google.com/identity/gsi/web/reference/js-reference#IdConfiguration)
> [Fix] move itp_support from google btn to conf

- projects/lib/src/directives/google-signin-button.directive.ts
"value" is showing in the console using the latest version of the library, I've deleted the line of code that is showing that text.
> console.log in ButtonDirective deleted

- projects/lib/src/providers/google-login-provider.ts
After signing in with Google, I wanted to omit the authentication screen and consent screen operations that are reopened when 'SocialAuthService::getAccessToken' is called.
https://developers.google.com/identity/oauth2/web/reference/js-reference#TokenClientConfig
add 'prompt' in GoogleInitOptions.
```
providers: [
CookieService,
{
provide: 'SocialAuthServiceConfig',
useValue: {
autoLogin: true,
providers: [
{
id: GoogleLoginProvider.PROVIDER_ID,
provider: new GoogleLoginProvider('xxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com',
{
scopes : environment.auth.scopes,
prompt : 'none'   // '' | 'none' | 'consent' |  'select_account'
}
),
}
]
} as SocialAuthServiceConfig,
```
> add: [Google]prompt property on initTokenClient

- projects/lib/src/directives/google-signin-button.directive.ts
Sing in with Google section on readme https://github.com/abacritt/angularx-social-login#sign-in-with-google has the following available options for `text`
text | string | 'signin_with','signup_with'or 'continue_with' | 'signin_with'
-- | -- | -- | --
This PR will fix missing `continue_with` type casting to the `text` input.
> Add `continue_with` to `text` allowed values

- projects/lib/src/directives/google-signin-button.directive.ts
- projects/lib/src/providers/google-login-provider.ts
fixing errors by changind import path:
- export 'take' (imported as 'take') was not found in 'rxjs'
- export 'take' (imported as 'skip') was not found in 'rxjs'
- export 'take' (imported as 'filter') was not found in 'rxjs'
found while installing the library in an angular 15 project
> fix: changing rxjs operators import

- projects/lib/src/providers/google-login-provider.ts
Developers will be migrated by default starting April 2024. Opt-in to FedCM (set [boolean flag to true](https://notifications.google.com/g/p/ANiao5ow5Tla6OVb28ojCX4O6gVIvYJVpJTgpO5ZqDn8ClkSy03xsGveEp8qriF6VMrcb4KMicqLdlW8hY9Ik9csZZykXFDIXQ0jD9YJYimTt9-2wTbRow5SekUllktEidF4Dq6LgFoT-dHNt8qA3MrJQuRpe8kdFFWyHEN2B_HRfjb_29ub6EGzBM0bH7j2g_SeVY0Bv2bNC5KRs3I9mopu_YnHK1bkog8e8L7-PudJm4WeOegzbX7PMj03Du8jcNQJWveTpXhX1kFblKHt)) to test and make any necessary changes to ensure a smooth transition.
Developers using [Automatic Sign-in](https://notifications.google.com/g/p/ANiao5oRGQb2zweGv-Ty4P1J8wmf99Q-wEMNk1tRoRXs15yH7wF7A24O7anQQmZEC8oAlWftKGPH4oX4aK-Jn8luOqzpuEFf1sTMoZbNrVBK7-LkEPjSWw2bMpMEgWyLNMPRI6Xw6pvE8qVql9N4VAUsCO1Vu89-1u22_k_83gz9zHmeYGQriHT1BONJqaUl-ha45YESNZhoosXHXmuITC-JxJRNb0I-7jAMa45GTB54 …
> Add option use_fedcm_for_prompt with same value than oneTapEnabled
